name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        standard: [c++11, c++14, c++17, c++23]

    steps:
      - uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build and test
        working-directory: tests
        run: make clean check CXX_VERSION=${{ matrix.standard }}

      - name: Build and test with sanitators
        working-directory: tests
        run: make clean check CXX_VERSION=${{ matrix.standard }} CXXFLAGS='-g -fsanitize=address,undefined'
